# This workflow checks that an [iTrac Id] is included in the PR title or body
# If the PR doesn't correspond to any iTrac issue, then '[no-issue]' should be present in the PR title or body

name: PR check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopene

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  title:
    name: PR Title/Body Verification
    runs-on: [ self-hosted, linux, apama ]
    # Do not run on Dependabot-generated PRs
    # - Firstly, it's pointless (all machine generated)
    # - Secondly, this won't get (sometimes necessary) write-access to the repo if triggered off of a Dependabot event ( https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events )
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checking PR Title and Body
        id: check-title-body
        run: |
          echo 'Title - ${{ github.event.pull_request.title }}'
          echo 'Body - ${{  github.event.pull_request.body }}'
          [[ '${{ github.event.pull_request.title }}' =~ ^.*\[PAB-[0-9]+\]|\[no-issue\].*$ ]] || [[ '${{ github.event.pull_request.description }}' =~ ^.*\[PAB-[0-9]+\]|\[no-issue\].*$ ]] && exit 0 || echo "missing-id=true" >> $GITHUB_OUTPUT
      - name: iTrac id missing in PR title/body
        if: ${{ steps.check-title.outputs.missing-id == 'true' }}
        run: |
          echo "::error ::iTrac id missing in PR title/body. Please add a either '[PAB-<id>]' or '[no-issue]' to your PR title/body."
          exit 1
